# Generated by Django 6.0.7 on 2026-07-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('icon', models.CharField(blank=True, max_length=200)),
                ('content_type', models.CharField(choices=[('tool', 'Tool'), ('game', 'Game'), ('project', 'Project'), ('resource', 'Resource')], default='tool', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
    ]
