# Generated by Django 6.0.7 on 2026-07-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contentitem_delete_tool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن اعلان')),
                ('link', models.URLField(blank=True, verbose_name='لینک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
            },
        ),
        migrations.AlterModelOptions(
            name='contentitem',
            options={'verbose_name': 'محتوا', 'verbose_name_plural': 'محتواها'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'تنظیمات سایت', 'verbose_name_plural': 'تنظیمات سایت'},
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='content_type',
            field=models.CharField(choices=[('webapp', 'Web App'), ('game', 'Game'), ('resource', 'Resource'), ('project', 'Useful Project')], default='tool', max_length=20),
        ),
    ]
