# Generated by Django 6.0.7 on 2026-07-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Vornex Tools', max_length=200)),
                ('description', models.TextField(default='Modern tools platform')),
                ('keywords', models.CharField(blank=True, max_length=300)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='seo/')),
            ],
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
