# Generated by Django 6.0.7 on 2026-07-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_seosettings_delete_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seosettings',
            name='title',
            field=models.CharField(default='Vornex Web App', max_length=200),
        ),
    ]
